server.port=8080

# MySQL 驱动（公共）
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 平台（公共）
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 文件上传限制（容器宽松接收，实际校验在应用层）
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# 照片存储目录
photo.upload-dir=${user.home}/photo-uploads


spring.profiles.active=dev